windows:
	x86_64-w64-mingw32-gcc main.c -L/usr/x86_64-w64-mingw32/lib -o ../build/I-Am-Synthetic.exe -lglfw3 -lgdi32

linux:
	gcc main.c  -o ../build/I-Am-Synthetic -lGLEW -lGL -lglfw3
osx:
	gcc main.c  -o ../build/I-Am-Synthetic -framework OpenGL -lGLEW -lglfw3 -g
